version: "3.8"
services:
  app:
    image: img_kivyapp
    container_name: kivy_app
    build:
      context: ./app
      dockerfile: Dockerfile
    expose:
      - 80
    tty: true
    ulimits:
      memlock: -1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./app/src/Lib:/app/Lib
      - ./database:/database
      - ${YOUR_IMAGE_DATASET_PATH}:/dataset
    environment:
      - DISPLAY=${YOUR_HOST_IP}:0


